SHELL = /bin/bash
R    ?= R 
RCMD =@$(R) CMD
all: boost_date_lag14.RData rf_date_lag14_weth.RData rp_date_only.RData \
	 rp_date_lag14_hol.RData rf_date_lag14_hol.RData mars_date_lag14_weth.RData \
	 pls_date_lag14_weth.RData boost_date_only.RData lm_date_lag14.RData \
	 glmn_date_lagall.RData mars_date_lag14_hol.RData rf_date_lag14.RData \
	 glmn_date_lag14.RData pls_date_lagall.RData svmr_date_lag14.RData \
	 pls_date_only.RData pls_date_lag14.RData rp_date_lag14.RData \
	 mars_date_only.RData svmr_date_only.RData pls_date_lag14_hol.RData \
	 rp_date_lag14_weth.RData glmn_date_lag14_hol.RData rf_date_only.RData \
	 rf_date_lagall.RData cb_date_only.RData cb_date_lag14_hol.RData \
	 mars_date_lagall.RData boost_date_lag14_hol.RData svmr_date_lagall.RData \
	 boost_date_lag14_weth.RData svmr_date_lag14_weth.RData cb_date_lagall.RData \
	 mars_date_lag14.RData lm_date_lag14_hol.RData glmn_date_lag14_weth.RData \
	 cb_date_lag14.RData lm_date_lagall.RData lm_date_only.RData \
	 cb_date_lag14_weth.RData rp_date_lagall.RData lm_date_lag14_weth.RData \
	 glmn_date_only.RData boost_date_lagall.RData svmr_date_lag14_hol.RData 

boost_date_lag14.RData: ../../Data_Sets/Chicago_trains/chicago.RData boost_date_lag14.R 
	 @date '+ %Y-%m-%d %H:%M:%S: starting  boost_date_lag14.R'
	 @$(RCMD) BATCH --vanilla boost_date_lag14.R
	 @date '+ %Y-%m-%d %H:%M:%S: finishing boost_date_lag14.R'

rf_date_lag14_weth.RData: ../../Data_Sets/Chicago_trains/chicago.RData rf_date_lag14_weth.R 
	 @date '+ %Y-%m-%d %H:%M:%S: starting  rf_date_lag14_weth.R'
	 @$(RCMD) BATCH --vanilla rf_date_lag14_weth.R
	 @date '+ %Y-%m-%d %H:%M:%S: finishing rf_date_lag14_weth.R'

rp_date_only.RData: ../../Data_Sets/Chicago_trains/chicago.RData rp_date_only.R 
	 @date '+ %Y-%m-%d %H:%M:%S: starting  rp_date_only.R'
	 @$(RCMD) BATCH --vanilla rp_date_only.R
	 @date '+ %Y-%m-%d %H:%M:%S: finishing rp_date_only.R'

rp_date_lag14_hol.RData: ../../Data_Sets/Chicago_trains/chicago.RData rp_date_lag14_hol.R 
	 @date '+ %Y-%m-%d %H:%M:%S: starting  rp_date_lag14_hol.R'
	 @$(RCMD) BATCH --vanilla rp_date_lag14_hol.R
	 @date '+ %Y-%m-%d %H:%M:%S: finishing rp_date_lag14_hol.R'

rf_date_lag14_hol.RData: ../../Data_Sets/Chicago_trains/chicago.RData rf_date_lag14_hol.R 
	 @date '+ %Y-%m-%d %H:%M:%S: starting  rf_date_lag14_hol.R'
	 @$(RCMD) BATCH --vanilla rf_date_lag14_hol.R
	 @date '+ %Y-%m-%d %H:%M:%S: finishing rf_date_lag14_hol.R'

mars_date_lag14_weth.RData: ../../Data_Sets/Chicago_trains/chicago.RData mars_date_lag14_weth.R 
	 @date '+ %Y-%m-%d %H:%M:%S: starting  mars_date_lag14_weth.R'
	 @$(RCMD) BATCH --vanilla mars_date_lag14_weth.R
	 @date '+ %Y-%m-%d %H:%M:%S: finishing mars_date_lag14_weth.R'

pls_date_lag14_weth.RData: ../../Data_Sets/Chicago_trains/chicago.RData pls_date_lag14_weth.R 
	 @date '+ %Y-%m-%d %H:%M:%S: starting  pls_date_lag14_weth.R'
	 @$(RCMD) BATCH --vanilla pls_date_lag14_weth.R
	 @date '+ %Y-%m-%d %H:%M:%S: finishing pls_date_lag14_weth.R'

boost_date_only.RData: ../../Data_Sets/Chicago_trains/chicago.RData boost_date_only.R 
	 @date '+ %Y-%m-%d %H:%M:%S: starting  boost_date_only.R'
	 @$(RCMD) BATCH --vanilla boost_date_only.R
	 @date '+ %Y-%m-%d %H:%M:%S: finishing boost_date_only.R'

lm_date_lag14.RData: ../../Data_Sets/Chicago_trains/chicago.RData lm_date_lag14.R 
	 @date '+ %Y-%m-%d %H:%M:%S: starting  lm_date_lag14.R'
	 @$(RCMD) BATCH --vanilla lm_date_lag14.R
	 @date '+ %Y-%m-%d %H:%M:%S: finishing lm_date_lag14.R'

glmn_date_lagall.RData: ../../Data_Sets/Chicago_trains/chicago.RData glmn_date_lagall.R 
	 @date '+ %Y-%m-%d %H:%M:%S: starting  glmn_date_lagall.R'
	 @$(RCMD) BATCH --vanilla glmn_date_lagall.R
	 @date '+ %Y-%m-%d %H:%M:%S: finishing glmn_date_lagall.R'

mars_date_lag14_hol.RData: ../../Data_Sets/Chicago_trains/chicago.RData mars_date_lag14_hol.R 
	 @date '+ %Y-%m-%d %H:%M:%S: starting  mars_date_lag14_hol.R'
	 @$(RCMD) BATCH --vanilla mars_date_lag14_hol.R
	 @date '+ %Y-%m-%d %H:%M:%S: finishing mars_date_lag14_hol.R'

rf_date_lag14.RData: ../../Data_Sets/Chicago_trains/chicago.RData rf_date_lag14.R 
	 @date '+ %Y-%m-%d %H:%M:%S: starting  rf_date_lag14.R'
	 @$(RCMD) BATCH --vanilla rf_date_lag14.R
	 @date '+ %Y-%m-%d %H:%M:%S: finishing rf_date_lag14.R'

glmn_date_lag14.RData: ../../Data_Sets/Chicago_trains/chicago.RData glmn_date_lag14.R 
	 @date '+ %Y-%m-%d %H:%M:%S: starting  glmn_date_lag14.R'
	 @$(RCMD) BATCH --vanilla glmn_date_lag14.R
	 @date '+ %Y-%m-%d %H:%M:%S: finishing glmn_date_lag14.R'

pls_date_lagall.RData: ../../Data_Sets/Chicago_trains/chicago.RData pls_date_lagall.R 
	 @date '+ %Y-%m-%d %H:%M:%S: starting  pls_date_lagall.R'
	 @$(RCMD) BATCH --vanilla pls_date_lagall.R
	 @date '+ %Y-%m-%d %H:%M:%S: finishing pls_date_lagall.R'

svmr_date_lag14.RData: ../../Data_Sets/Chicago_trains/chicago.RData svmr_date_lag14.R 
	 @date '+ %Y-%m-%d %H:%M:%S: starting  svmr_date_lag14.R'
	 @$(RCMD) BATCH --vanilla svmr_date_lag14.R
	 @date '+ %Y-%m-%d %H:%M:%S: finishing svmr_date_lag14.R'

pls_date_only.RData: ../../Data_Sets/Chicago_trains/chicago.RData pls_date_only.R 
	 @date '+ %Y-%m-%d %H:%M:%S: starting  pls_date_only.R'
	 @$(RCMD) BATCH --vanilla pls_date_only.R
	 @date '+ %Y-%m-%d %H:%M:%S: finishing pls_date_only.R'

pls_date_lag14.RData: ../../Data_Sets/Chicago_trains/chicago.RData pls_date_lag14.R 
	 @date '+ %Y-%m-%d %H:%M:%S: starting  pls_date_lag14.R'
	 @$(RCMD) BATCH --vanilla pls_date_lag14.R
	 @date '+ %Y-%m-%d %H:%M:%S: finishing pls_date_lag14.R'

rp_date_lag14.RData: ../../Data_Sets/Chicago_trains/chicago.RData rp_date_lag14.R 
	 @date '+ %Y-%m-%d %H:%M:%S: starting  rp_date_lag14.R'
	 @$(RCMD) BATCH --vanilla rp_date_lag14.R
	 @date '+ %Y-%m-%d %H:%M:%S: finishing rp_date_lag14.R'

mars_date_only.RData: ../../Data_Sets/Chicago_trains/chicago.RData mars_date_only.R 
	 @date '+ %Y-%m-%d %H:%M:%S: starting  mars_date_only.R'
	 @$(RCMD) BATCH --vanilla mars_date_only.R
	 @date '+ %Y-%m-%d %H:%M:%S: finishing mars_date_only.R'

svmr_date_only.RData: ../../Data_Sets/Chicago_trains/chicago.RData svmr_date_only.R 
	 @date '+ %Y-%m-%d %H:%M:%S: starting  svmr_date_only.R'
	 @$(RCMD) BATCH --vanilla svmr_date_only.R
	 @date '+ %Y-%m-%d %H:%M:%S: finishing svmr_date_only.R'

pls_date_lag14_hol.RData: ../../Data_Sets/Chicago_trains/chicago.RData pls_date_lag14_hol.R 
	 @date '+ %Y-%m-%d %H:%M:%S: starting  pls_date_lag14_hol.R'
	 @$(RCMD) BATCH --vanilla pls_date_lag14_hol.R
	 @date '+ %Y-%m-%d %H:%M:%S: finishing pls_date_lag14_hol.R'

rp_date_lag14_weth.RData: ../../Data_Sets/Chicago_trains/chicago.RData rp_date_lag14_weth.R 
	 @date '+ %Y-%m-%d %H:%M:%S: starting  rp_date_lag14_weth.R'
	 @$(RCMD) BATCH --vanilla rp_date_lag14_weth.R
	 @date '+ %Y-%m-%d %H:%M:%S: finishing rp_date_lag14_weth.R'

glmn_date_lag14_hol.RData: ../../Data_Sets/Chicago_trains/chicago.RData glmn_date_lag14_hol.R 
	 @date '+ %Y-%m-%d %H:%M:%S: starting  glmn_date_lag14_hol.R'
	 @$(RCMD) BATCH --vanilla glmn_date_lag14_hol.R
	 @date '+ %Y-%m-%d %H:%M:%S: finishing glmn_date_lag14_hol.R'

rf_date_only.RData: ../../Data_Sets/Chicago_trains/chicago.RData rf_date_only.R 
	 @date '+ %Y-%m-%d %H:%M:%S: starting  rf_date_only.R'
	 @$(RCMD) BATCH --vanilla rf_date_only.R
	 @date '+ %Y-%m-%d %H:%M:%S: finishing rf_date_only.R'

rf_date_lagall.RData: ../../Data_Sets/Chicago_trains/chicago.RData rf_date_lagall.R 
	 @date '+ %Y-%m-%d %H:%M:%S: starting  rf_date_lagall.R'
	 @$(RCMD) BATCH --vanilla rf_date_lagall.R
	 @date '+ %Y-%m-%d %H:%M:%S: finishing rf_date_lagall.R'

cb_date_only.RData: ../../Data_Sets/Chicago_trains/chicago.RData cb_date_only.R 
	 @date '+ %Y-%m-%d %H:%M:%S: starting  cb_date_only.R'
	 @$(RCMD) BATCH --vanilla cb_date_only.R
	 @date '+ %Y-%m-%d %H:%M:%S: finishing cb_date_only.R'

cb_date_lag14_hol.RData: ../../Data_Sets/Chicago_trains/chicago.RData cb_date_lag14_hol.R 
	 @date '+ %Y-%m-%d %H:%M:%S: starting  cb_date_lag14_hol.R'
	 @$(RCMD) BATCH --vanilla cb_date_lag14_hol.R
	 @date '+ %Y-%m-%d %H:%M:%S: finishing cb_date_lag14_hol.R'

mars_date_lagall.RData: ../../Data_Sets/Chicago_trains/chicago.RData mars_date_lagall.R 
	 @date '+ %Y-%m-%d %H:%M:%S: starting  mars_date_lagall.R'
	 @$(RCMD) BATCH --vanilla mars_date_lagall.R
	 @date '+ %Y-%m-%d %H:%M:%S: finishing mars_date_lagall.R'

boost_date_lag14_hol.RData: ../../Data_Sets/Chicago_trains/chicago.RData boost_date_lag14_hol.R 
	 @date '+ %Y-%m-%d %H:%M:%S: starting  boost_date_lag14_hol.R'
	 @$(RCMD) BATCH --vanilla boost_date_lag14_hol.R
	 @date '+ %Y-%m-%d %H:%M:%S: finishing boost_date_lag14_hol.R'

svmr_date_lagall.RData: ../../Data_Sets/Chicago_trains/chicago.RData svmr_date_lagall.R 
	 @date '+ %Y-%m-%d %H:%M:%S: starting  svmr_date_lagall.R'
	 @$(RCMD) BATCH --vanilla svmr_date_lagall.R
	 @date '+ %Y-%m-%d %H:%M:%S: finishing svmr_date_lagall.R'

boost_date_lag14_weth.RData: ../../Data_Sets/Chicago_trains/chicago.RData boost_date_lag14_weth.R 
	 @date '+ %Y-%m-%d %H:%M:%S: starting  boost_date_lag14_weth.R'
	 @$(RCMD) BATCH --vanilla boost_date_lag14_weth.R
	 @date '+ %Y-%m-%d %H:%M:%S: finishing boost_date_lag14_weth.R'

svmr_date_lag14_weth.RData: ../../Data_Sets/Chicago_trains/chicago.RData svmr_date_lag14_weth.R 
	 @date '+ %Y-%m-%d %H:%M:%S: starting  svmr_date_lag14_weth.R'
	 @$(RCMD) BATCH --vanilla svmr_date_lag14_weth.R
	 @date '+ %Y-%m-%d %H:%M:%S: finishing svmr_date_lag14_weth.R'

cb_date_lagall.RData: ../../Data_Sets/Chicago_trains/chicago.RData cb_date_lagall.R 
	 @date '+ %Y-%m-%d %H:%M:%S: starting  cb_date_lagall.R'
	 @$(RCMD) BATCH --vanilla cb_date_lagall.R
	 @date '+ %Y-%m-%d %H:%M:%S: finishing cb_date_lagall.R'

mars_date_lag14.RData: ../../Data_Sets/Chicago_trains/chicago.RData mars_date_lag14.R 
	 @date '+ %Y-%m-%d %H:%M:%S: starting  mars_date_lag14.R'
	 @$(RCMD) BATCH --vanilla mars_date_lag14.R
	 @date '+ %Y-%m-%d %H:%M:%S: finishing mars_date_lag14.R'

lm_date_lag14_hol.RData: ../../Data_Sets/Chicago_trains/chicago.RData lm_date_lag14_hol.R 
	 @date '+ %Y-%m-%d %H:%M:%S: starting  lm_date_lag14_hol.R'
	 @$(RCMD) BATCH --vanilla lm_date_lag14_hol.R
	 @date '+ %Y-%m-%d %H:%M:%S: finishing lm_date_lag14_hol.R'

glmn_date_lag14_weth.RData: ../../Data_Sets/Chicago_trains/chicago.RData glmn_date_lag14_weth.R 
	 @date '+ %Y-%m-%d %H:%M:%S: starting  glmn_date_lag14_weth.R'
	 @$(RCMD) BATCH --vanilla glmn_date_lag14_weth.R
	 @date '+ %Y-%m-%d %H:%M:%S: finishing glmn_date_lag14_weth.R'

cb_date_lag14.RData: ../../Data_Sets/Chicago_trains/chicago.RData cb_date_lag14.R 
	 @date '+ %Y-%m-%d %H:%M:%S: starting  cb_date_lag14.R'
	 @$(RCMD) BATCH --vanilla cb_date_lag14.R
	 @date '+ %Y-%m-%d %H:%M:%S: finishing cb_date_lag14.R'

lm_date_lagall.RData: ../../Data_Sets/Chicago_trains/chicago.RData lm_date_lagall.R 
	 @date '+ %Y-%m-%d %H:%M:%S: starting  lm_date_lagall.R'
	 @$(RCMD) BATCH --vanilla lm_date_lagall.R
	 @date '+ %Y-%m-%d %H:%M:%S: finishing lm_date_lagall.R'

lm_date_only.RData: ../../Data_Sets/Chicago_trains/chicago.RData lm_date_only.R 
	 @date '+ %Y-%m-%d %H:%M:%S: starting  lm_date_only.R'
	 @$(RCMD) BATCH --vanilla lm_date_only.R
	 @date '+ %Y-%m-%d %H:%M:%S: finishing lm_date_only.R'

cb_date_lag14_weth.RData: ../../Data_Sets/Chicago_trains/chicago.RData cb_date_lag14_weth.R 
	 @date '+ %Y-%m-%d %H:%M:%S: starting  cb_date_lag14_weth.R'
	 @$(RCMD) BATCH --vanilla cb_date_lag14_weth.R
	 @date '+ %Y-%m-%d %H:%M:%S: finishing cb_date_lag14_weth.R'

rp_date_lagall.RData: ../../Data_Sets/Chicago_trains/chicago.RData rp_date_lagall.R 
	 @date '+ %Y-%m-%d %H:%M:%S: starting  rp_date_lagall.R'
	 @$(RCMD) BATCH --vanilla rp_date_lagall.R
	 @date '+ %Y-%m-%d %H:%M:%S: finishing rp_date_lagall.R'

lm_date_lag14_weth.RData: ../../Data_Sets/Chicago_trains/chicago.RData lm_date_lag14_weth.R 
	 @date '+ %Y-%m-%d %H:%M:%S: starting  lm_date_lag14_weth.R'
	 @$(RCMD) BATCH --vanilla lm_date_lag14_weth.R
	 @date '+ %Y-%m-%d %H:%M:%S: finishing lm_date_lag14_weth.R'

glmn_date_only.RData: ../../Data_Sets/Chicago_trains/chicago.RData glmn_date_only.R 
	 @date '+ %Y-%m-%d %H:%M:%S: starting  glmn_date_only.R'
	 @$(RCMD) BATCH --vanilla glmn_date_only.R
	 @date '+ %Y-%m-%d %H:%M:%S: finishing glmn_date_only.R'

boost_date_lagall.RData: ../../Data_Sets/Chicago_trains/chicago.RData boost_date_lagall.R 
	 @date '+ %Y-%m-%d %H:%M:%S: starting  boost_date_lagall.R'
	 @$(RCMD) BATCH --vanilla boost_date_lagall.R
	 @date '+ %Y-%m-%d %H:%M:%S: finishing boost_date_lagall.R'

svmr_date_lag14_hol.RData: ../../Data_Sets/Chicago_trains/chicago.RData svmr_date_lag14_hol.R 
	 @date '+ %Y-%m-%d %H:%M:%S: starting  svmr_date_lag14_hol.R'
	 @$(RCMD) BATCH --vanilla svmr_date_lag14_hol.R
	 @date '+ %Y-%m-%d %H:%M:%S: finishing svmr_date_lag14_hol.R'

